/*
 * MESSAGE1.H
 *
 *  Created on: May 6, 2025
 *      Author: elois
 */

#ifndef MESSAGE_H_
#define MESSAGE_H_


#include <stdint.h>

extern const char *intro_string_1;
extern const char *intro_string_2;
extern const char *intro_string_3;

extern const char *string_to_send2a;
extern const char *string_to_send2b;
extern const char *string_to_send2c;
extern const char *string_to_send2d;

extern const char *string_to_send3a;
extern const char *string_to_send3b;
extern const char *string_to_send3c;

extern const char *string_to_send4;

extern const char *back_to_starta;
extern const char *back_to_startb;
extern const char *back_to_startc;
#endif /* MESSAGE1_H_ */
